version: '3.9'

services:
  financial-db:
    image: postgres:15
    container_name: financial_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${FINANCIAL_DB_NAME}
      POSTGRES_USER: ${FINANCIAL_DB_USER}
      POSTGRES_PASSWORD: ${FINANCIAL_DB_PASSWORD}
    ports:
      - "${FINANCIAL_DB_PORT}:5432"
    volumes:
      - financial_db_data:/var/lib/postgresql/data

  financial-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial_service
    restart: unless-stopped
    depends_on:
      - financial-db
      - rabbitmq  
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${FINANCIAL_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${FINANCIAL_DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq   
      SPRING_RABBITMQ_PORT: 5672       
      SPRING_RABBITMQ_USERNAME: admin  
      SPRING_RABBITMQ_PASSWORD: secret123 
    ports:
      - "8083:8080"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: financial_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  financial_db_data:
