server:
  port: 8080

spring:
  application:
    name: ordering-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://ordering-db:3306/orderingdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:ordering_user}
    password: ${SPRING_DATASOURCE_PASSWORD:ordering_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5673}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:secret123}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
