apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-mysql
  template:
    metadata:
      labels:
        app: customer-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-env
                  key: CUSTOMER_DB_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: customer-env
                  key: CUSTOMER_DB_NAME

            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: customer-env
                  key: CUSTOMER_DB_USER

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customer-env
                  key: CUSTOMER_DB_PASSWORD
