version: "3.9"

services:

  # ==========================
  # RabbitMQ for Delivery
  # ==========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: delivery_rabbitmq
    ports:
      - "5673:5672"     # different port so it doesn't conflict with customer-service
      - "15673:15672"   # management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - delivery_net

  # ==========================
  # Delivery Database
  # ==========================
  delivery-db:
    image: mysql:8
    container_name: delivery_mysql
    restart: always
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DELIVERY_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DELIVERY_DB_NAME}
      MYSQL_USER: ${DELIVERY_DB_USER}
      MYSQL_PASSWORD: ${DELIVERY_DB_PASSWORD}
    volumes:
      - DELIVERY_data:/var/lib/mysql
    networks:
      - DELIVERY_net

  # ==========================
  # Delivery Service
  # ==========================
  delivery-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DELIVERY_service
    restart: always
    depends_on:
      - delivery-db
      - rabbitmq
    ports:
      - "8082:8080"
    env_file:
      - .env.DELIVERY
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://delivery-db:3306/${DELIVERY_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${DELIVERY_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DELIVERY_DB_PASSWORD}
    networks:
      - delivery_net

networks:
  delivery_net:

volumes:
  delivery_data:
