version: "3.9"

services:
  # ==========================
  # RabbitMQ
  # ==========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: ordering_rabbitmq
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret123
    networks:
      - ordering_net

  # ==========================
  # Ordering Database
  # ==========================
  ordering-db:
    image: mysql:8
    container_name: ordering_mysql
    restart: unless-stopped
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ORDERING_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ORDERING_DB_NAME}
      MYSQL_USER: ${ORDERING_DB_USER}
      MYSQL_PASSWORD: ${ORDERING_DB_PASSWORD}
    volumes:
      - ordering_data:/var/lib/mysql
    networks:
      - ordering_net

  # ==========================
  # Ordering Service
  # ==========================
  ordering-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordering_service
    restart: unless-stopped
    depends_on:
      - ordering-db
      - rabbitmq
    env_file:
      - .env.ordering
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ordering-db:3306/${ORDERING_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${ORDERING_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDERING_DB_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: secret123
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8082:8080"
    volumes:
      - C:/Users/natas/.m2:/root/.m2
    networks:
      - ordering_net

networks:
  ordering_net:

volumes:
  ordering_data:

