server:
  port: 8080

spring:
  application:
    name: delivery-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://delivery-db:3306/deliverydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:delivery_user}
    password: ${SPRING_DATASOURCE_PASSWORD:delivery_pwd}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initializationFailTimeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5673}
    username: ${RABBITMQ_USER:admin}
    password: ${RABBITMQ_PASSWORD:secret123}

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
